### ISSUE TITLE
autocomplete not working for injected classes

### ISSUE THREAD

**Issue by tfriedel** [kodemore/kink#11]
Thanks for making this nice minimal library! I'm giving it a try for a project currently.
One thing I noticed, when I use classes that are decorated with ```@inject```, the autocompletion or display of signature parameters in jupyter notebooks doesn't work. 
I didn't dive into the source, but maybe you can use some of the suggestions mentioned here:
https://hynek.me/articles/decorators/

**Comment by dkraczkowski** [comment]
@tfriedel I will have a look in my spare time. Thanks for your feedback.

**Comment by tfriedel** [comment]
I tried
```py
from functools import wraps
...
@wraps(service)
    def _decorated(*args, **kwargs):
```
and this solved the problem with autocomplete. 

As described in the article, fuctools.wraps still has some shortcomings. I also tried wraps from boltons.functools and this also worked, with the added benefit that the inspection of the decorated function looked identical to the un-decorated function. I suggest you vendor the boltons functools module.

Now we still haven't solved it for asyncio. It could work in the same way, but I haven't tried it!

**Comment by dkraczkowski** [comment]
I didn't have lately much time to look into `boltons.functools` but will do this at some point. I need to understand how much of a performance impact it can cause and whether it is worth adding it knowing the all the drawback (if any). Thank you for your contribution and support.

**Comment by dkraczkowski** [comment]
The following is reference for the latest build with your fix: https://github.com/kodemore/kink/actions/runs/836243567
