### ISSUE TITLE
How to have Constructor injection when I have one parameters which I do not want to inject via kink?

### ISSUE THREAD

**Issue by rohts-patil** [kodemore/kink#15]
Example:-
```
# Set Dependencies

di['logger'] = logger

@inject
class A:
     def __init__(logger, extra_variable):
          self.logger=logger
          self.extra_variable=extra_variable
```
Now, here logger is injected by kink, but how should I create the object when I need to set extra_variable also in constructor?

Also, does kink has support of setter based injection?

Thank you

**Comment by dkraczkowski** [comment]
Hello @rohts-patil. You can simply do:
```
instance = A(extra_variable=True)
```

> Also, does kink has support of setter based injection?
Not yet.

**Comment by rohts-patil** [comment]
Thanks @dkraczkowski
