### ISSUE TITLE
[QUESTION] How kink works with async?

### ISSUE THREAD

**Issue by katunilya** [kodemore/kink#32]
Hi! 

First of all, thanks for such simple and useful DI!

In readme it is said that `kink` support "async with `asyncio`" however I don't see any examples of such functionality. Is it possible to create some fastapi-like async dependency?

Concrete case (`sqlalchemy`'s `AsyncSesssion`):

```py
async def get_session() -> AsyncSession:
    async_session = sessionmaker(
        engine, class_=AsyncSession, expire_on_commit=False
    )
    async with async_session() as session:
        yield session
```

I tried I few workaround, but all of them just does not work, as `kink` understands (as it seems to me) only lambda-based factory functions.

**Comment by dkraczkowski** [comment]
@katunilya Hello, thank you. Well I think it was a bit of a overstatement. What I meant is kink can inject dependencies into your async functions.

Your usecase is a very interesting thou, and sounds like a good feature request.

**Comment by katunilya** [comment]
@dkraczkowski thanks for quick response!

Truly I thinks it might be a great feature.
