### ISSUE TITLE
No support for https://peps.python.org/pep-0563/

### ISSUE THREAD

**Issue by jrosiek** [kodemore/kink#34]
Kink resolves type annotations at runtime. According do PEP-0563 (https://peps.python.org/pep-0563/) an additional code is required to extract type information at runtime.

**Comment by dkraczkowski** [comment]
@jrosiek I am sorry, could you please elaborate a bit more on what you mean?

**Comment by dkraczkowski** [comment]
Also please provide an example of a failing code.
